/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#dfc573",
        "secondary-fixed-dim": "#b6d300",
        "on-tertiary-fixed": "#231b00",
        "primary-fixed": "#ffdadb",
        "surface-container": "#1e2022",
        "on-surface": "#e3e2e6",
        "surface-container-lowest": "#0d0e11",
        "error": "#ffb4ab",
        "primary": "#ffb2b8",
        "on-surface-variant": "#e4bdbf",
        "outline-variant": "#5b3f41",
        "on-primary-fixed-variant": "#91002c",
        "on-error-container": "#ffdad6",
        "surface": "#121316",
        "on-primary-container": "#ffffff",
        "graphite-base": "#0d0d0e",
        "on-secondary-fixed": "#181e00",
        "on-tertiary-container": "#4e3e00",
        "primary-container": "#e32652",
        "on-tertiary-fixed-variant": "#564500",
        "tertiary-fixed-dim": "#dfc572",
        "tertiary-fixed": "#fce18b",
        "on-secondary-fixed-variant": "#404c00",
        "surface-container-high": "#292a2d",
        "silver-mist": "#9ea0a9",
        "deep-slate": "#272c33",
        "secondary-container": "#d0f100",
        "error-container": "#93000a",
        "surface-tint": "#ffb2b8",
        "surface-container-highest": "#343538",
        "outline": "#ab888a",
        "surface-bright": "#38393c",
        "on-error": "#690005",
        "surface-variant": "#343538",
        "inverse-surface": "#e3e2e6",
        "on-tertiary": "#3c2f00",
        "secondary-fixed": "#d0f100",
        "pitch-black": "#000000",
        "pure-white": "#ffffff",
        "on-primary-fixed": "#40000f",
        "surface-dim": "#121316",
        "tertiary-container": "#c3aa5a",
        "surface-container-low": "#1a1b1e",
        "on-primary": "#67001d",
        "inverse-on-surface": "#2f3033",
        "background": "#121316",
        "on-background": "#e3e2e6",
        "on-secondary-container": "#5c6b00",
        "primary-fixed-dim": "#ffb2b8",
        "inverse-primary": "#be003d",
        "secondary": "#ffffff",
        "on-secondary": "#2c3400"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "sm": "16px",
        "xl": "64px",
        "lg": "48px",
        "base": "4px",
        "container-margin": "32px",
        "md": "24px",
        "gutter": "16px",
        "xs": "8px"
      },
      fontFamily: {
        "label-caps": ["Inter", "sans-serif"],
        "display-lg": ["Anton", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "display-xl": ["Anton", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-serif": ["Playfair Display", "serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-xl": ["80px", { "lineHeight": "0.85", "letterSpacing": "-0.04em", "fontWeight": "400" }],
        "body-lg": ["20px", { "lineHeight": "1.45", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "display-lg": ["64px", { "lineHeight": "0.90", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "headline-serif": ["64px", { "lineHeight": "1.1", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "1.45", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.45", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
